### ISSUE TITLE
Truncated leading zeros from events’ topics

### ISSUE THREAD

**Issue by ArranKitson** [TokenFlowInsights/EDW-Feedback#1]
This does not change the values but adds a bit of additional complexity to the decoding process. This is already fixed for new data and can be easily fixed for existing records just by database update.

**Comment by tmierzwa** [comment]
The history of events is fixed and all topics are now properly padded to uniform 66 char length.

**Comment by tmierzwa** [comment]
The test query returns 0 rows.
```
select count(*)
from edw.raw.events
where length(topic0) < 66 or length(topic1) < 66 or 
      length(topic2) < 66 or length(topic3) < 66;
```
